### PR TITLE
Customize Homepage using BootStrap and SCSS

### PR DESCRIPTION
**Pull request by PrantoshB**
# Hello There 👋🏽 

hello

In this PR, I have:

- Added and configured Slider on Homepage
- Customized Homepage using BootStrap and SCSS

## Screenshot:

Screenshot 2023-05-28 at 12 18 50 AM

### Prantosh

### CODE REVIEW

**Comment by PrantoshB** [comment]
Kindly look into the Desktop version and leave your comments, I'll push the mobile version today. Then you can give your final opinions.

Thanks,
Prantosh

**Review by haliljon — APPROVED** [review]
Hi @PrantoshB , 👋   

The task is completed!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

68747470733a2f2f36342e6d656469612e74756d626c722e636f6d2f38376530623634363963393537626638393663646563316361623634366163662f74756d626c725f696e6c696e655f706b316264616b434370317270637239615f3530302e676966

## Highlights
- No linter error ✅ 
- Descriptive PR title and Summary ✅ 
- Gitflow used ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
# This will be the final version if you guys agree.

## Screenshot of the mobile version :

Screenshot 2023-05-28 at 12 19 32 PM

**Comment by yetemegn-telaye** [comment]
Hi @PrantoshB  😊, 



Your changes are complete! 

## Highlights
✅ Great presentation of the mobile version
✅ App functions work properly
✅ Great responsive design of homepage
✅ Awesome design for the service cards
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

------

**Comment by PrantoshB** [comment]
Thanks @yetemegn-telaye for reviewing ❤️ . I am merging it now 🚀

**Pull request merged**
